### ISSUE TITLE
fork this

### ISSUE THREAD

**Issue by jlanga** [GenomicResources/test_repo_for_forking#1]
@SofiMarcos 

Sí, al ser privado no se puede hacer fork

**Comment by SofiMarcos** [comment]
A, entiendo!

**Comment by jlanga** [comment]
La dinámica es:
- Haces un fork y aparece como un repo tuyo
- Haces en tu repo los cambios que quieres hacer
- Pulsas el botón de compare & pull request
- Y ya el dueño del repo original decide si aceptar tus cambios o rechazarlos.

Sube un gif y prueba

**Comment by SofiMarcos** [comment]
Creo que puedo hacer cambios directamente, sin que sean sugerencias.

**Comment by SofiMarcos** [comment]
En caso de no querer que la gente haga cambios, creo que hay que crear un new branch

**Comment by jlanga** [comment]
Los branches son para dar un nombre al tema de los cambios que vas a sugerir. Es más para desarrollo de software que para organizarnos.

**Comment by jlanga** [comment]
A la derecha hay un botón para que no te lleguen las notificaciones al email cada vez que alguien habla.
